/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "servidorAlmacenamiento.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
init_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, init, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
storemessage_1(char *topic, char *msg, int *clnt_res,  CLIENT *clnt)
{
	storemessage_1_argument arg;
	arg.topic = topic;
	arg.msg = msg;
	return (clnt_call (clnt, storeMessage, (xdrproc_t) xdr_storemessage_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getlastmessage_1(char *topic, char **clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, getLastMessage,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &topic,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}
