/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidorAlmacenamiento.h"
#include "fileManager.h"

bool_t
init_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	*result = fm_init();
	retval = *result == 0 ? TRUE : FALSE;

	return retval;
}

bool_t
storemessage_1_svc(char *topic, char *msg, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	*result = fm_storeMessage(topic, msg);
	retval = *result == 0 ? TRUE : FALSE;

	return retval;
}

bool_t
getlastmessage_1_svc(char *topic, char **result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	*result = (char*) malloc(1025);
	int ret = fm_getLastMessage(topic, *result);

	retval = ret == 0 ? TRUE : FALSE;

	return retval;
}

int
servidor_almacenamiento_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
