/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "servidorAlmacenamiento.h"

bool_t
xdr_storemessage_1_argument (XDR *xdrs, storemessage_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->topic, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->msg, ~0))
		 return FALSE;
	return TRUE;
}
